[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npx nuxt build"]

[start]
cmd = "npx prisma migrate deploy && node .output/server/index.mjs"
