erDiagram
    USERS {
        string id PK
        string email
        string password
        string name
        datetime createdAt
        datetime updatedAt
    }
    PREDICTIONS {
        string id PK
        string userId FK
        string namaProduk
        string kategori
        string subKategori
        int hargaProduk
        float predictionScore
        int predictionLabel
        string insight
        datetime createdAt
    }
    PRODUCTS {
        string id PK
        string url
        string namaProduk
        string kategori
        string subKategori
        string marketplace
        string lokasi
        string namaToko
        int hargaProduk
        int jumlahTerjual
        float rating
        float popularityScore
        int hargaTier
        datetime createdAt
    }

    USERS ||--o{ PREDICTIONS : "memiliki"
